### ISSUE TITLE
Might be worth switching from shikashi to eval_in

### ISSUE THREAD

**Issue by JoshCheek** [tyrbo/turingbot#2]
I've got a similar issue of needing to eval code safely, so wrote a gem, [eval_in](https://github.com/JoshCheek/eval_in) that ships it off to https://eval.in/

Advantages:
- The guy who wrote the service, Charlie Somerville, really knows what he's doing, so it's probably secure. But even if it's not, it's not your computer that burns down :)
- It's much simpler to have the service evaluate it than to figure out how to configure a security gem, and constantly be battling ability vs security.
- EvalIn is < 200 loc, and has no gem dependencies, so (other than the Net::HTTP setup) is simpler to understand/modify
- Supports [many languages](https://github.com/JoshCheek/eval_in#what-languages-can-this-run), so some fun places to grow to

Disadvantages:
- It's two network calls (POST the code, then GET the evaluated result), so will add latency.
- Because it's a network resource, can have outages that you don't control.

IDK if it's right for TuringBot, but figured I'd mention it so you could consider it.

**Comment by evanphx** [comment]
Really good idea, I'd do this. Offloading the security of running the code is a very good call.

**Comment by tyrbo** [comment]
Done and done. Doesn't seem -that- much slower. Nice to not have to worry about looking through scary methods in Kernel, or worrying about things that could be hidden away in other places I'm not aware of.
